import "./globals.scss";

import { Figtree } from "next/font/google";

import Navbar from "../components/navbar";
import Footer from "../components/footer";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
